### ISSUE TITLE
Access to attribute in "templates/default/my.cnf.erb"

### ISSUE THREAD

**Issue by JAG-01** [chef-cookbooks/mysql#281]
Feature request to provide access to attributes found in "templates/default/my.cnf.erb" such as "pid-file", "log-error" and "socket".
```
# Chef generated my.cnf for instance mysql-myappname

[client]
default-character-set          = utf8
port                           = 3306
socket                         = /run/mysql-myappname/mysqld.sock

[mysql]
default-character-set          = utf8

[mysqld]
user                           = mysql
pid-file                       = /run/mysql-myappname/mysqld.pid
socket                         = /run/mysql-myappname/mysqld.sock
port                           = 3306
datadir                        = /var/lib/mysql-myappname
tmpdir                         = /tmp
log-error                      = /var/log/mysql-myappname/error.log
!includedir /etc/mysql-myappname/conf.d

[mysqld_safe]
socket                         = /run/mysql-myappname/mysqld.sock
```
*This issue created as requested in issue https://github.com/chef-cookbooks/mysql/issues/280.

**Comment by flatrocks** [comment]
Yep... with the v6 mysql cookbook, it's virtually impossible to set up proper client connections from other apps without knowing the (non-standard) socket, for example.

**Comment by someara** [comment]
I just added a quick patch to make the socket configurable.

I'll add the rest of them in 6.1

https://github.com/chef-cookbooks/mysql/commit/9ef63c617283dad228b1324c94c1b1af805ce493

Released as 6.0.12

**Comment by idwright** [comment]
Can you please make sure you include tmpdir and include the apparmor configuration 
Thanks.

**Comment by geleman** [comment]
I agree with all these changes. We should be able to chose the data_dir, error_log, tmpdir, socket, and pid file. tmpdir in particular because it should be placed in memory and no on disk, which is what hard coding it to /tmp is doing. We should also be able to determine the location of the my.cnf file.

**Comment by flatrocks** [comment]
The things you might reasonably want to do in my.cnf could be endless.  One solution would be to change the hard coded cookbook attribute for my.cnf template in ```mysql/libraries/provider_mysql_service.rb```:
``` ruby
        # Main configuration file
        template "#{new_resource.name} :create #{etc_dir}/my.cnf" do
          ...
          cookbook 'mysql'
          ...
            )
          action :create
        end
```
to something schematically like:
``` ruby
        # Main configuration file
        template "#{new_resource.name} :create #{etc_dir}/my.cnf" do
          ...
          cookbook new_resource.mycnf_template_cookbook if new_resource.mycnf_template_cookbook
          ...
            )
          action :create
        end
```
Default cookbook would still be ```mysql``` but alternatively, you could use a custom template in a wrapper.  That would avoid complicating things for most applications, while providing ultimate flexibility for special needs.  We use this a lot to provide future flexibility while avoiding lots of YAGNI code.  Omitting settings from the cnf file can have the result of picking up distro/package defaults and it seems like trying to hardcode proper defaults for a full-featured my.cnf template in each context would be a huge task.
  _Pardon me if details are wrong due to Friday afternoon effects, but you get the idea._

(Of course doesn't provide a way to use a non-standard my.cnf location.)

**Comment by geleman** [comment]
@flatrocks that looks like a good solution. I'm currenlty trying to figure out if I can rewrite some of this to be able to control the directory structures. I'm new to Ruby so it's been an adventure so far. If I can just get the directories how I want them I can write a wrapper to create my default my.cnf for my environment.

**Comment by someara** [comment]
These should all be tunable now as of 6.1.0... There are explicit knobs for the main my.cnf managed by a mysql_service, and an mysqld_options hash property as well. Enjoy!
