### ISSUE TITLE
Remote root access not granted when data_dir = /var/lib/mysql

### ISSUE THREAD

**Issue by Umofomia** [chef-cookbooks/mysql#285]
It appears when the MySQL package is installed, by default it sets up all the initial tables under `/var/lib/mysql`. Because of this, when `data_dir` is set to `/var/lib/mysql`, [this condition](https://github.com/chef-cookbooks/mysql/blob/584d284e3b85787a45a7788589bb5a4566b58b27/libraries/provider_mysql_service.rb#L147) for skipping the initialization of the mysql database is satisfied and the task is skipped:

```ruby
not_if "/usr/bin/test -f #{parsed_data_dir}/mysql/user.frm"
```

This same task is supposed to also notifiy `bash[#{new_resource.name} :create initial records]`, which grants remote root access. Because the task is not run, remote root access is also not granted.

This was encountered on a clean Ubuntu 14.04 box when attempting to install MySQL version 5.6.

**Comment by someara** [comment]
This is by design...

There's no way to "short circuit" the Debian packages to prevent them from running their post-installation scripts. They automatically initialize that database, and do a bunch of goofy things like creating a debian-sys-maint user that makes replication a pain.

The strategy is to avoid it all together. Bonus points: by using non-standard directories for instances, we can avoid anyone getting hurt during package upgrades.

At one point I thought about trying to do some sort of "first run" magic by writing a file marker somewhere,  and blowing that directory away, but that doesn't account for situations like this:

mount "/var/lib/mysql" do
  device ebs_vol_dev
  action :mount
end

mysql_service 'something' do
  data_dir ''/var/lib/mysql"
end

^ In that scenario, even on the "first chef run", we definitely don't want to blow away the contents of the database and re-initialize it.

So... yea. You're going to have to use another directory for data_dir.

README PR's accepted clarifying this ;)

-s
