### ISSUE TITLE
Restrictions on initial root password

### ISSUE THREAD

**Issue by maoueh** [chef-cookbooks/mysql#287]
I had set an initial root password having both a `$` and a `!` in it. Looking like this `MyPa$$wordHasSpecialChars!`.

The cookbook is converging correctly, however, I was simply not able to connect to the database after convergence. 

My guess is that they are treated as special symbols by the bash script setting the password. This was working before, at least in version `5.x` of the cookbook.

**Comment by someara** [comment]
Hi.

I won't be able to get to this for a few days, (traveling)  but I know exactly how to fix it if you want to take a crack at it. Otherwise, these are notes for myself ;)

Use the Shellwords library to escape the string.

https://github.com/chef-cookbooks/mysql/blob/v5.6.1/libraries/provider_mysql_service_rhel.rb#L2
https://github.com/chef-cookbooks/mysql/blob/v5.6.1/libraries/provider_mysql_service_rhel.rb#L142

Change the smoke test recipe to use the broken password (mysql_replication_test)

https://github.com/chef-cookbooks/mysql/blob/master/test/fixtures/cookbooks/mysql_replication_test/recipes/default.rb#L4

Run test-kitchen against any version of any platform as a smoke test, and it'll be good

**Comment by someara** [comment]
Fixed in 6.0.13
