### ISSUE TITLE
Why 'yum-mysql-community' cookbook is required for ubuntu/debian flavor of Linux? 

### ISSUE THREAD

**Issue by xbeta** [chef-cookbooks/mysql#293]
I thought in an `apt-get` world, `yum` don't apply, or am I missing something here? 

```ruby
supports 'debian'
supports 'ubuntu'

depends 'yum-mysql-community'
```

Welcome any type of explanation on this. @someara

**Comment by someara** [comment]
The mysql cookbook supports debian based distros as well as rhel based
distros (also solarish, and soon, windows.).

The dependency system isn't smart enough to know if chef-client *might*
need to use something.. it has no concept of what yum, apt, smf, etc are.
They're just strings representations of cookbook artifacts with version
numbers.

I always like to make the comparison to libkrb5.
OS Packages often depend on it, even though the user has no intention of
using that particular functionality.

-s

**Comment by xbeta** [comment]
For some reasons, my chef can't locate cookbook for `yum-mysql-community`.  And I'm on Ubuntu, so I'm not sure why I need to care about yum at all.  I understand the required dependencies for RHEL, but I don't think this should be part of the global `metadata.rb`

**Comment by someara** [comment]
Use Berkshelf to resolve your dependency set.
Test-kitchen handles this automatically, but you can do a "berks vendor"
into a chef-repo otherwise.

This cookbook is cross platform, and therefore depends on
yum-mysql-community, even though those code paths never get fired on
Ubuntu.

This cookbook also depends on SMF, even though its rarely ran on Solaris.
Future versions will require apt-something to fill out version support on
debuntu.
Future versions will also require the windows cookbook, to get access to
the resources shipped there.

The alternative would be to completely decouple dependencies, which I'm not
willing to do.

-s
