### ISSUE TITLE
SQL query LWRP

### ISSUE THREAD

**Issue by paweloczadly** [chef-cookbooks/mysql#296]
That would be cool if the cookbook could provide a LWRP for SQL query.

This LWRP could contain the following attributes:
* as_user
* with_password
* socket

Here could  be the example:

```ruby
mysql_query 'CREATE DATABASE IF NOT EXISTS test;' do
  as_user 'root'
  with_password 'root'
  socket '/var/mysql/mysql.sock'
end
```

**Comment by someara** [comment]
There's a :query action on the mysql_database resource in the database cookbook.
That should let you do what you're looking to accomplish.

Right now, it is shipped in a separate cookbook, since it's implemented with the mysql2 gem, and therefore requires a compiler to build the native extension. Breaking it out from this cookbook lets us not have a dependency on build-essential.

-s
