### ISSUE TITLE
NoMethodError for version 5.6.1

### ISSUE THREAD

**Issue by jslusher** [chef-cookbooks/mysql#299]
I'm trying to use version of this cookbook because it was the last version that allowed for setting a repl password in the mysql_service lwrp. I am getting the following:

`  mysql2_chef_gem[default] action install
  
    Error executing action `install` on resource 'mysql2_chef_gem[default]'
    
    NoMethodError
    -------------
    undefined method `version' for Chef::Resource::MysqlClient

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:17:in `block (2 levels) in <class:Mysql>'
    /var/chef/cache/cookbooks/mysql2_chef_gem/libraries/provider_mysql2_chef_gem_mysql.rb:16:in `block in <class:Mysql>'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/database/recipes/mysql.rb

      2: mysql2_chef_gem 'default' do
      3:   client_version node['mysql']['version'] if node['mysql']
      4:   action :install
      5: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/database/recipes/mysql.rb:2:in `from_file'

    mysql2_chef_gem("default") do
      action [:install]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "database"
      recipe_name "mysql"
    end
`

I can't figure out the right combination of versioning to get this to work again.

**Comment by someara** [comment]
The mysql2_chef_gem depends on the 6.x version of the mysql cookbook to get access to the multiple version support in the mysql_client resource. 5.x did not have this.

You should really upgrade to the 6.x series. Managing the repl password with Chef wasn't appropriate, since what you're really doing is managing a database table. It was breaking replication left and right due to every server node considering itself the source of truth for that record.

-s

**Comment by jslusher** [comment]
It's worked just fine for me in my configuration for the better part of 6 months. It was providing me a way to set that password so that a deployment of a mysql instance would automatically join as a slave without any further manual intervention.
