### ISSUE TITLE
posibility to upgrade mysql

### ISSUE THREAD

**Issue by ramonskie** [chef-cookbooks/mysql#310]
it would be nice to have the ability to upgrade mysql
this is not possible at the moment because when installing a newer version
dpkg want to know if you want to keep/change files

**Comment by someara** [comment]
Are you trying to upgrade from a machine previously built with the mysql cookbook, or a random state?
What mysql/os versions, etc

**Comment by ramonskie** [comment]
trying to upgrade from a machine that was previously built with the mysql cookbook

**Comment by nkadel-skyhook** [comment]
This is a *nightmare* to automate. The big problem on RHEL based systems is the 'mysql-libs' package, and all the version specific packages from the community repository that replace it. Removing that package requires an "rpm -e --nodeps mysql-libs' or similar step with the relevant community mysql-community-libs RPM, and it will break all packages with dependencies on it. This particularly includes the nagios-plugins-check_mysql package and postfix.

So a separate "Revert to OS mysql" recipe might be workable, with those caveats, but it *will* break things while running and should be a one-off, not a normally run process.

**Comment by someara** [comment]
For all Linux, the 6.x series mysql_service resource uses non-standard pathing to get out of the package manager's way. 

For debian/ubuntu, things are are particularly weird because there is no way to stop the package post-inst from initializing the database, the debian-sys-maint, etc.

I just spot checked updating 5.5 -> 5.6 on ubuntu-14.04.

Indeed, it exploded on the modified /etc/init/mysql.conf... there's not really a good way around this because of the nature of the package manager. Manually upgrading should be easy enough, but I'd recommend rebuilding the box if you keep your data_dir on a separate partition / mount.

For centos, 

I just spot checked upgrading 5.6 to 5.7 on centos via the version attribute. It updated the package repos and made 5.7 available. 

You'll have to manually install the new version via yum upgrade mysql-community-server, but it worked.
Again, I'd recommend rebuilding the box if you keep your data_dir on a separate partition / mount.

-s
