### ISSUE TITLE
Cannot find a resource for mysql_service

### ISSUE THREAD

**Issue by mgdevstack** [chef-cookbooks/mysql#380]
mysql_service resource is not found for ubuntu14.04. What might be the solution on this ?

![mysql_service](https://cloud.githubusercontent.com/assets/8110509/9958650/d26252a0-5e29-11e5-8112-d32da82b0f32.PNG)

**Comment by till** [comment]
@mg-stack missing `depends` in your `lamp/metadata.rb`

**Comment by nkadel-skyhook** [comment]
I was just referred to http://stackoverflow.com/questions/31051890/chef-failed-to-install-mysql-no-resouce-method-or-variable-named-create, which provides the workaround of adding "provider Chef::Provider::MysqlService::Sysvinit"' to the the specific "mysql_service" stanza.

It fixed the problem for me, using chefdb-0.9.0 and chef-solo. The problem didn't seem to have occur with older chefdk releases. That does make me wonder if it the issue was introduced when adding chef compatibility for systemd.

**Comment by AjeetK** [comment]
Regarding service manager, you can alternatively try `sysvinit` or `upstart` as explained [here](http://jee-appy.blogspot.com/2017/01/mysql-service-manager-chef-amazon.html)
