### ISSUE TITLE
Issues with special chars in initial_root_password

### ISSUE THREAD

**Issue by alexandrezia** [chef-cookbooks/mysql#390]
I'm using a strong initial_root_password which contains several special chars like:   ^*[+ etc. , and this line:
https://github.com/chef-cookbooks/mysql/blob/master/libraries/helpers.rb#L124
Is completely ruining the password, as it is escaping all special chars for use in a shell, but it is used in a mysql function PASSWORD() not in a shell.
So, If I change this line from:
```
Shellwords.escape(new_resource.initial_root_password)
```
To:
```
new_resource.initial_root_password
```
It works as expected.
So please, remove ```Shellwords.escape``` from the initial password, so we can use strong passwords with special chars.
Thanks

**Comment by acoulton** [comment]
I have the same issue - the link in the original issue above is out dated but the shell escaping still happens, at https://github.com/chef-cookbooks/mysql/blob/master/libraries/helpers.rb#L307

Currently it's not possible to start an instance with a strong password - the password is set, but of course then the mysql box is unreachable because the stored password has the undesired escaping.
