### ISSUE TITLE
Mysql server 5.6 on Debian 8

### ISSUE THREAD

**Issue by MatthieuMota** [chef-cookbooks/mysql#399]
I've no try, but possible to override attributes mysql package for install mysql-server-5.6 on debian 8 ? Of course if i use third repo for apt.

**Comment by iennae** [comment]
@MatthieuMota 

The mysql_server_installation_package has a package_name option where you can override what package is installed. Check out https://github.com/chef-cookbooks/mysql/blob/master/libraries/mysql_server_installation_package.rb. If this doesn't answer your question, please open a new issue so that the github issue template is used and make sure to fill out all the sections. Thanks!
