### ISSUE TITLE
Is it sane to hardcode package versions within the cookbook?

### ISSUE THREAD

**Issue by wilb** [chef-cookbooks/mysql#476]
Following on from the spate of bugs opened as a result of the MySQL security fixes that went out over the last few days, I'd like to question the logic of why each package version is hard coded to a specific package? I mentioned this in the 16.04  bug report specifically, but thought it wise to open a specific ticket to discuss this. 

It would seem absolutely sensible to give users the option to pin to a specific package via a property of the resource, but surely the default behaviour should be to use the version offered up by the operating system's package manager?

I noticed in another thread that someone has worked around this by passing in `:package_version ''` to their mysql_server resource, but that doesn't help when other cookbooks utilise it in their own manner (eg the `mysql2_chef_gem` resource calling `mysql_client`)

**Comment by rmyates** [comment]
+1 I've just run into this myself, it seems far far too restrictive as it relies on the cookbook maintainers to keep an eye on the latest package versions across every linux distribution and push a new cookbook version each time there's a change. I don't think that's realistic.

Personally I use an aptly mirror to tightly control package versions in our production+dev+test environments to take hard coded version control out of cookbooks which was proving too hard to maintain in my team.

**Comment by lamont-granquist** [comment]
Yes, its insane.

Fastest way to fix it would be to submit a PR.

What is not clear is if there's some reason for it.  In particular I'm worried around keeping the API so that someone can submit `major_version "5.6"` and get 5.6.x

It looks like some of the shape of the API may be that installing `package "mysql" { version "5.6.x.yadda.yadda" }` will use the virtual package name to pick the correct `mysql-server-5.6` package that offers the "5.6.x" version.  It may be necessary to expand the matching of distro + version to package names in `default_client_package_name` and `default_server_package_name` to create functions that return not just the default, but return the correct package name for any major version on any distro.

At any rate, its clear to everyone that this is a bad pattern.

**Comment by flatrocks** [comment]
This sounds radical but the obvious solution seems to be to *completely eliminate the ``default_package_version`` helper*, let the ``package_version`` property just naturally default to _nil_.

The version would then default to whatever the distro package managers provide, the latest stable version, which is what we do for everything else anyway.

What am I missing?   My perspective is only MySQL/Ubuntu, perhaps this is not feasible for other combinations?

**Comment by wilb** [comment]
This seems like the sanest way to fix it - I've manually overridden it with a blank string in my resources. It should be optional rather than explicit.

**Comment by lamont-granquist** [comment]
Isn't the issue here that distros ship multiple different "major_version"s of mysql -- e.g. 5.5.x, 5.6.x, 5.7.x -- and that the cookbook needs to know which version you want in order to set it up correctly and then the package manager needs to install the right "major_version"?

Eliminating the helper gets the common case correct when you just want to take whatever the default is for the distro, but if you want to pick something different from the default then what do you do?

There's clearly other solutions here, though.  One possibility is that you choose either a default of `nil` (meaning track the default in the distro, and we use some static mapping to know that a given distro defaults to 5.6.x or something) or else you force the user to fully pin the mysql package version "5.7.11-1.el5" and then pull the 5.7 off the start of that string for use as the "major_version".  You could also require the user to specify the package they want to install and to specify the major_version (for all I know maybe you can already do this?  haven't dug into the full shape of the api...)

**Comment by wilb** [comment]
Certainly in the Debian / Ubuntu world its very rare for a distro to have two major versions of mysql, but if they do then different major versions have different package names; you don't need the explicit minor details of a version number if you do want a specific release. On Ubuntu 16.04 `mysql-server-5.7` is the package name and `mysql-server` also exists as a metapackage which points to the default for the distro. 

>>> if you want to pick something different from the default then what do you do?
Just allow the user to pass in a proprety that gets passed to the `version` property of the package resource? When calling the package resource `version` isn't a requirement, but it's utilised if it's passed in. As it stands the version is always passed in.

The thing that is frustrating as an end user is that this cookbook seems to have tried to cater for some very complicated edge cases, but instead has actually created more problems for most real world scenarios than it's solved as a result. Lots of other community cookbooks offer similar cross platform installation support without these headaches; in fact this very cookbook used to "just work" in these scenarios. Hopefully we can all come to a common consensus and a bit of refactoring will be all that's needed to make it more usable when the distros push their security updates out.

**Comment by lamont-granquist** [comment]
The problem is that you do need to have the cookbook support people using the different major versions, and you do need to at least optionally support full version pinning.  And I'd agree that its the edge cases that are messing up the cookbook, but I think some of that is based on the shape of the API and that the cookbook is trying to do too much.  For example, if you want full version pinning having to specify both the major version and the exact package version you want to use _should_ mitigate this problem.  Largely its the magic that is trying to convert "5.7" into "5.7.15-0ubuntu0.16.04.1" which is causing the problem and i'd agree it may be better to just force the user that wants that behavior to specify both.  I think its reasonable to expect people that want to pin to type more and potentially type in redundant information.  However, I don't agree that its that complicated of an edge case -- exact version pinning in production is a pretty basic requirement.

And we may actually be mostly in agreement.  I agree the `default_package_version` helper needs to go, I just want to make sure that we still support explicit version pins.  I'm also a little worried that the helper fell out of the API design and that the API design may need to change somewhat in order to delete it.

Probably better to discuss this in a PR where there's actual code changes though.  I haven't had the time to tear this cookbook open and figure out what its doing and why, so I can only talk in hand-wavey fashion that simply deleting the helper worries me.  If you submit a PR to delete the helper, then you'll necessarily have to confront any issues that come up and then we can discuss real code, and I might be all worried about nothing...
