### ISSUE TITLE
Bad sysvinit documentation

### ISSUE THREAD

**Issue by micahlagrange** [chef-cookbooks/mysql#515]
https://supermarket.chef.io/cookbooks/mysql#readme

### Cookbook version
8.2.0

### Chef-client version
12+

### Platform Details
Ubuntu 14.04

### Scenario:
Use the documented feature:
`provider Chef::Provider::MysqlServiceSysvinit`

Results in an error:
`[2017-03-07T17:11:54+00:00] ERROR: uninitialized constant Chef::Provider::MysqlServiceSysvinit`

### Steps to Reproduce:
Create a resource like so:
```
mysql_service node['some-instance-name'] do
  version '5.6'
  port node['some-port']
  data_dir node['some-data_dir']
  initial_root_password node['some-root-password']
  provider Chef::Provider::MysqlServiceSysvinit
  action [:create, :start]
end
```

### Expected Result:
The cookbook should succeed and sysvinit should be configured

### Actual Result:
You get the above error

The appropriate method should be documented. I don't know the fix yet.

**Comment by iennae** [comment]
The default init provider with Ubuntu 14.04 is upstart. You don't need the provider line. Are you trying to use Sysvinit instead of upstart? You'll note the line "Chef selects the appropriate provider based on platform and version, but you can specify one if your platform support it." underneath providers. If you leave the provider line off it should start up fine.
